import pyfiglet
import subprocess
ascii_banner = pyfiglet.figlet_format(text="Deploy Kubernetes", font="xtimes")
print(ascii_banner)
print("######################################################################")
print("## El script recibe 4 parametros de entrada                         ##")
print("## El primero es la ruta donde se encuentra el dockerfile.          ##")
print("## El segundo es el nombre de la imagen.                            ##")
print("## El tercero es la direccion y nombre del configmap                ##")
print("## El cuarto es la direccion y nombre del archivo de deployment.    ##")
print("######################################################################")
ruta_docker = input("Ingrese la ruta relativa al directorio del script o absoluta donde se encuentra el dockerfile: ")
print()
nombre_imagen = input("Ingrese el nombre de la imagen: ")
print()
direccion_configmap = input("Ingrese ruta del archivo configmap: ")
print()
direccion_deploy = input("Ingrese ruta del archivo deployment: ")
print()
subprocess.call(['sh','./deploy_minikube.sh', ruta_docker, nombre_imagen, direccion_configmap, direccion_deploy])